# Generated by Django 5.2.7 on 2026-01-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
